### ISSUE TITLE
Non-draggable Tool Tips

### ISSUE THREAD

**Issue by PollyC-FAST** [fast-graphs/fastgraphs-beta#1]
**Describe the bug**
Cannot move pop-up windows to unblock graph.

**Screenshots**
![image](https://user-images.githubusercontent.com/78382224/106513870-85121880-64a1-11eb-8e32-abc59c1154d8.png)

**Desktop (please complete the following information):**
Apple iPad Pro model ML0R2LL/A, 12.9" screen, 128GB memory 
iPadOS 14.4
Chrome browser version 87.0.4280.77 

**Additional context**
Bug:
Cannot move pop-up windows to unblock graph.

Dave

**Comment by Coltcarnevle** [comment]
fixed and being released with next release
