### ISSUE TITLE
Custom Valuation Line - Does Not Show Up In Forecasting Graph

### ISSUE THREAD

**Issue by PollyC-FAST** [fast-graphs/fastgraphs-beta#13]
**Describe the bug**
Custom valuation line doesn’t seem to carry over to forecasting module
The NUMBER is in FAST FACTS - but no line on Forecasting Graph

**Screenshots**
![image](https://user-images.githubusercontent.com/78382224/106612310-f8b23500-6536-11eb-9fb3-eb72eaca36e0.png)

**Comment by Coltcarnevle** [comment]
@PollyC-FAST this seems to be fixed

**Comment by PollyC-FAST** [comment]
@Coltcarnevle yes, the Custom Valuation Line is fixed!
