### ISSUE TITLE
FROM CHUCK - Windowdressing/Bolding

### ISSUE THREAD

**Issue by PollyC-FAST** [fast-graphs/fastgraphs-beta#21]
**Describe the bug**
Chuck is suggesting maybe bolding the titles highlighted in yellow in the screenshot:

![image](https://user-images.githubusercontent.com/78382224/106785286-3c7e6a80-661b-11eb-8866-dabb82bad171.png)

**Comment by Coltcarnevle** [comment]
done and testing
