### ISSUE TITLE
Why is Polly's Beta Screenshot Different than Beta Tester Brian Cosco's??????

### ISSUE THREAD

**Issue by PollyC-FAST** [fast-graphs/fastgraphs-beta#35]
**Describe the bug**
SPG - Simon Property
Why is Polly's Screenshot different than Brian's?  
**I can't duplicate what he is showing me**.:  From Brian:  "Lets look at ticker symbol  SPG.  Under the performance tab, under the heading " adjusted earnings div payout ratio" u will notice a column of numbers such as 54.69M%, 70.32M%, 51.00M% and so on.  The letter M does not belong in this list of  numbers.  It should read 54.69% , 70.32%, and 51.00% . . .  Lets look at ticker symbol  SPG again.  On the historical tab over to the right , half way down in blue it shows the Normal P/E ratio as 18347745.10.
  P/E ratios are normally only 2 or 3 digit numbers - in this case it should be  only 18 or 18.3"

![image](https://user-images.githubusercontent.com/78382224/107261801-c0ff2d80-6a0d-11eb-86a5-b71e80c75928.png)
![image](https://user-images.githubusercontent.com/78382224/107261809-c3fa1e00-6a0d-11eb-94fc-f142107756a3.png)

**Comment by Coltcarnevle** [comment]
@PollyC-FAST Brian is using Free Cash Flow, you are using Adjusted Earnings

**Comment by Coltcarnevle** [comment]
One issue though is that the performance results are not changing the name to free cash flow
