### ISSUE TITLE
FORECASTING - Performance Pop-Up Disappears When Curser is Moved Away

### ISSUE THREAD

**Issue by PollyC-FAST** [fast-graphs/fastgraphs-beta#43]
When you click on any forward point in time you get your pop-up - (Screenshot 1) - the pop-up should stay there if you move your mouse away, it does not (Screenshot 2)
![image](https://user-images.githubusercontent.com/78382224/107529100-88379380-6b88-11eb-9902-7a246a02ebe7.png)
![image](https://user-images.githubusercontent.com/78382224/107529117-8c63b100-6b88-11eb-936d-52e8c6b36cd5.png)

**Comment by Coltcarnevle** [comment]
@PollyC-FAST this is now fixed, but we haven't released yet to the public
